Repository officeluv/cxml-ruby, pull requests merged in 2020-03, with the labels that each got.

#9 chg:dev: Allow initialization from JSON serialization of instances
  lib/cxml/accounting.rb
  lib/cxml/address.rb
  lib/cxml/contact.rb
  lib/cxml/credential.rb
  lib/cxml/distribution.rb
  lib/cxml/document.rb
  lib/cxml/header.rb
  lib/cxml/item_detail.rb
  lib/cxml/item_id.rb
  lib/cxml/item_in.rb
  lib/cxml/item_out.rb
  lib/cxml/money.rb
  lib/cxml/order_request.rb
  lib/cxml/order_request_header.rb
  lib/cxml/protocol.rb
  lib/cxml/punch_out_order_message.rb
  lib/cxml/punch_out_order_message_header.rb
  lib/cxml/punch_out_setup_request.rb
  lib/cxml/punch_out_setup_response.rb
  lib/cxml/request.rb
  lib/cxml/response.rb
  lib/cxml/sender.rb
  lib/cxml/status.rb
Labels: enhancement

#11 Fix up for rubocop and expose ShipTo on PunchOutSetupRequest
  cxml.gemspec
  lib/cxml.rb
  lib/cxml/contact.rb
  lib/cxml/document.rb
  lib/cxml/extrinsic.rb
  lib/cxml/invoice.rb
  lib/cxml/invoice/invoice_detail_item.rb
  lib/cxml/invoice/invoice_detail_line_item_reference.rb
  lib/cxml/invoice/invoice_detail_order.rb
  lib/cxml/invoice/invoice_detail_summary.rb
  lib/cxml/invoice/invoice_distribution.rb
  lib/cxml/invoice/invoice_generator.rb
  lib/cxml/invoice/invoice_header.rb
  lib/cxml/invoice/invoice_request.rb
  lib/cxml/invoice/invoice_taxes.rb
  lib/cxml/punch_out_setup_request.rb
  lib/cxml/request.rb
  lib/cxml/ship_to.rb
  spec/credential_spec.rb
  spec/cxml_spec.rb
  spec/document_spec.rb
  spec/invoice/invoice_detail_line_item_reference_spec.rb
  spec/invoice/invoice_detail_order_spec.rb
  spec/invoice/invoice_detail_order_summary_spec.rb
  spec/invoice/invoice_distribution_spec.rb
  spec/invoice/invoice_generator_spec.rb
  spec/invoice/invoice_header_spec.rb
  spec/invoice/invoice_request_spec.rb
  spec/invoice/invoice_taxes_spec.rb
  spec/item_detail_spec.rb
  spec/item_id_spec.rb
  spec/item_in_spec.rb
  spec/money_spec.rb
  spec/parser_spec.rb
  spec/protocol_spec.rb
  spec/punch_out_order_message_header_spec.rb
  spec/punch_out_order_message_spec.rb
  spec/punch_out_setup_request_spec.rb
  spec/request_spec.rb
  spec/response_spec.rb
  spec/sender_spec.rb
  spec/spec_helper.rb
  spec/status_spec.rb
  spec/support/helpers.rb
Labels: documentation, enhancement

#12 fix:usr: set buyer cookie in rendering of Punchout Order Message
  lib/cxml/punch_out_order_message.rb
  spec/fixtures/punch_out_order_message_doc.xml
  spec/punch_out_order_message_spec.rb
Labels: bug
